List<String> people = [
      'abdullatif',
      'ehloma',
      'shahad',
      'mohamed',
      'marwa',
      'khaled',
      'hussin',
      'abdulrahman',
    ],
    images = [
      'assets/images/user-1.jpg',
      'assets/images/user-2.jpg',
      'assets/images/user-3.jpg',
      'assets/images/user-4.jpg',
      'assets/images/user-5.jpg',
      'assets/images/user-6.jpg',
      'assets/images/user-7.jpg',
      'assets/images/user-8.jpg',
    ],
    postImages = [
      'assets/images/user-1.jpg',
      'assets/images/user-2.jpg',
      'assets/images/user-3.jpg',
      'assets/images/user-4.jpg',
      'assets/images/user-5.jpg',
      'assets/images/user-6.jpg',
      'assets/images/user-7.jpg',
      'assets/images/user-8.jpg',
    ],
    postLiked = [
      'ehloma',
      'abdullatif',
      'marwa',
      'hussin',
      'khaled',
      'shahad',
      'abdulrahman',
      'mohamed',
    ],
    postNumberLiked = [
      '750',
      '843',
      '398',
      '243',
      '637',
      '271',
      '122',
      '192',
    ];
